<a href="https://colab.research.google.com/github/waqqasansari/lets_Play_with_PyTorch/blob/master/1_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [8]:
#multiplying two numpy array

a = np.array([2,3])
b = np.array([6,7])

N = a * b
print(N)
print(type(N)) #print the type of N

[12 21]
<class 'numpy.ndarray'>


In [7]:
#Same operation in Pytorch tensors

aT = torch.tensor([2,3])
bT = torch.tensor([6,7])

A = aT * bT
print(A)
print(type(A))  #print the type of A

tensor([12, 21])
<class 'torch.Tensor'>


In [16]:
torch.tensor([1.2, 3]).dtype #Automatic float tensor intialization

torch.set_default_dtype(torch.float64)

torch.tensor([1.2, 3]).dtype

torch.float64

In [17]:
#convert tensor to numpy
z = torch.tensor([3,4])

z.numpy()

array([3, 4])

In [19]:
#convert numpy to tensor
zn = np.array([3,4])

torch.from_numpy(a)

tensor([2, 3])

In [35]:
yt = torch.tensor([[2,3],[4,5]])
print(yt)
print(yt.size()) #size of tensor

tensor([[2, 3],
        [4, 5]])
torch.Size([2, 2])


In [22]:
#convert the tensors into floats
torch.FloatTensor([[2,3],[4,5]])

tensor([[2., 3.],
        [4., 5.]], dtype=torch.float32)

In [23]:
#create a random tensor
torch.rand(4,5)

tensor([[0.9246, 0.3507, 0.2466, 0.5519, 0.8590],
        [0.9447, 0.4610, 0.3296, 0.6285, 0.4968],
        [0.8406, 0.0467, 0.1810, 0.7030, 0.2316],
        [0.1711, 0.5076, 0.1972, 0.4680, 0.4881]])

In [24]:
#create a tensor of ones
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [27]:
zn = torch.tensor([[3,4],[5,6]])
print(f'sum: {zn.sum()}')

sum: 18


In [32]:
xc = torch.tensor([[3,4],[5,6]])
print(xc)
print("---+++++------++++++------")
print(xc.t()) #tensor transpose 

tensor([[3, 4],
        [5, 6]])
---+++++------++++++------
tensor([[3, 5],
        [4, 6]])


In [37]:
ay = torch.tensor([[6,4],[8,4]])

zt = ay.add(xc) #adding two tensors

zt

tensor([[ 9,  8],
        [13, 10]])

In [38]:
#in place addition
ay.add_(xc)

ay

tensor([[ 9,  8],
        [13, 10]])

In [39]:
#Run pytorch on GPU
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')